analysis:
  analysis_completed: true
  last_analyzed: '2025-08-13T20:30:58.351265'
  memory_files_created: false
  tech_stack:
  - git
  - kubernetes
  - python
api_keys:
  openai: sk-invalid
mcp_servers:
- args:
  - -y
  - '@modelcontextprotocol/server-filesystem'
  command: npx
  enabled: true
  name: filesystem
  type: official
mcp_tokens: {}
preferences:
  default_model: auto
  max_parallel_tasks: 5
  memory_enabled: true
